### ISSUE TITLE
Push SF OAuth2 support to upstream Xamarin.Auth repo

### ISSUE THREAD

**Issue by zgramana** [xamarin/SalesforceSDK#17]

**Comment by moljac** [comment]
Salesforce specifics remained in the SF repo, but the Xamarin.Auth code integrated in SF repo was cut out and replaced wit Xamarin.Auth nuget dependency.

This fixed several bugs:

*	28 Intermittent NSURLErrorDomain error -999			
	https://github.com/xamarin/SalesforceSDK/issues/28			
*	15 Add PCL support		
	https://github.com/xamarin/SalesforceSDK/issues/15
        Added with nuget bite-n-switch support and Windows* platforms

Closing
