### ISSUE TITLE
Intermittent NSURLErrorDomain error -999

### ISSUE THREAD

**Issue by ClintFrancis** [xamarin/SalesforceSDK#28]
The login screen is intermittently displaying "Authentication Error. The operation couldn't be completed. NSURLErrorDomain error -999" before any attempt is made to login.

To replicate it all you need to do is publish the sample code for iOS that comes with the component. Eventually it will start showing the error - in my experience its 1 in about every 4 or 5 runs.

NSURLErrorDomain error -999 == NSURLErrorCancelled.

The explanation:
"Returned when an asynchronous load is canceled. A Web Kit framework
delegate will receive this error when it performs a cancel operation on a
loading resource. Note that an NSURLConnection or NSURLDownload delegate
will not receive this error if the download is canceled."

**Comment by moljac** [comment]
solved in 1.3.2.x nuget.

Clsoing
